//sg
package xmltomysql;
/**
 * This class is responsible for flattening the xml generated by worldbankdataparsing in a format
 * suitable for loading into "vals" table of the world bank database.
 * @author aman
 *
 */
public class FlattenXML {

}
